dataset_path: '/content/drive/MyDrive/thumbnails128x128/*/*'
image_size: 32
batch_size: 16
z_dim: 512
lr_generator: 0.001
lr_discriminator: 0.001
epochs: 10
information_steps: 100
save_steps: 1000
discriminator_path: '/content/drive/MyDrive/Styleganmodel/discriminator_step_21.pt'
generator_path: '/content/drive/MyDrive/Styleganmodel/generator_step_21.pt'
